-- Create and select database
CREATE DATABASE IF NOT EXISTS travel_planner;
USE travel_planner;

-- Users table (authentication)
CREATE TABLE IF NOT EXISTS users (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50)  NOT NULL UNIQUE,
    email    VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,         -- bcrypt hash
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Places table (fetched from API or pre-seeded)
CREATE TABLE IF NOT EXISTS places (
    id        INT AUTO_INCREMENT PRIMARY KEY,
    name      VARCHAR(150) NOT NULL,
    category  VARCHAR(50)  NOT NULL,        -- food, beach, museum, etc.
    latitude  DECIMAL(10, 7),
    longitude DECIMAL(10, 7),
    rating    DECIMAL(3, 1) DEFAULT 0.0,
    city      VARCHAR(100),
    tags      VARCHAR(255),                 -- comma-separated keywords
    environment_type   VARCHAR(20) DEFAULT 'Mixed',
    physical_intensity  VARCHAR(20) DEFAULT 'Medium'
);

-- Itineraries table (saved plans per user)
CREATE TABLE IF NOT EXISTS itineraries (
    id         INT AUTO_INCREMENT PRIMARY KEY,
    user_id    INT  NOT NULL,
    trip_name  VARCHAR(100),
    destination VARCHAR(100),
    budget     VARCHAR(20),
    num_days   INT,
    preferences JSON,
    pacing_style VARCHAR(20) DEFAULT 'Moderate',
    companion_type VARCHAR(30) DEFAULT 'Solo',
    transport_mode VARCHAR(20) DEFAULT 'Public',
    accommodation_lat DECIMAL(10, 7),
    accommodation_lng DECIMAL(10, 7),
    status VARCHAR(20) DEFAULT 'Active',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Itinerary items (places per day per trip)
CREATE TABLE IF NOT EXISTS itinerary_items (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    itinerary_id INT NOT NULL,
    day_number   INT NOT NULL,
    place_id     INT NOT NULL,
    sequence_order INT NOT NULL DEFAULT 1,
    estimated_duration INT DEFAULT 60,
    is_locked   BOOLEAN DEFAULT FALSE,
    swap_history INT DEFAULT 0,
    FOREIGN KEY (itinerary_id) REFERENCES itineraries(id) ON DELETE CASCADE,
    FOREIGN KEY (place_id)     REFERENCES places(id)
);

-- Explicit feedback captured from the itinerary page.
CREATE TABLE IF NOT EXISTS trip_feedback (
    id            INT AUTO_INCREMENT PRIMARY KEY,
    itinerary_id   INT NOT NULL,
    user_id        INT NOT NULL,
    place_id       INT NOT NULL,
    rating_type    VARCHAR(20) NOT NULL,
    feedback_notes TEXT,
    created_at     DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_trip_feedback (itinerary_id, user_id, place_id),
    FOREIGN KEY (itinerary_id) REFERENCES itineraries(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id)      REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (place_id)     REFERENCES places(id) ON DELETE CASCADE
);

-- Weather alerts and smart suggestions generated by the live monitor.
CREATE TABLE IF NOT EXISTS weather_alerts (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    itinerary_id INT NOT NULL,
    alert_key    VARCHAR(100) NOT NULL,
    alert_type   VARCHAR(40) NOT NULL,
    headline     VARCHAR(200) NOT NULL,
    message      TEXT NOT NULL,
    payload      JSON,
    is_active    BOOLEAN DEFAULT TRUE,
    created_at   DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at   DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    resolved_at  DATETIME NULL,
    notification_signature VARCHAR(128),
    notification_sent_at DATETIME NULL,
    UNIQUE KEY unique_weather_alert (itinerary_id, alert_key),
    FOREIGN KEY (itinerary_id) REFERENCES itineraries(id) ON DELETE CASCADE
);

-- Firebase Cloud Messaging tokens for device push notifications.
CREATE TABLE IF NOT EXISTS push_tokens (
    id              INT AUTO_INCREMENT PRIMARY KEY,
    user_id         INT NOT NULL,
    token           TEXT NOT NULL,
    token_hash      CHAR(64) NOT NULL,
    platform        VARCHAR(40) DEFAULT 'web',
    user_agent      VARCHAR(255),
    created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_push_token (user_id, token_hash),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Admin login accounts managed from the Sprint 5 admin dashboard.
CREATE TABLE IF NOT EXISTS admin_accounts (
    id            INT AUTO_INCREMENT PRIMARY KEY,
    username      VARCHAR(50) NOT NULL UNIQUE,
    email         VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    is_active     BOOLEAN DEFAULT TRUE,
    created_at    DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at    DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Audit log for admin account changes and retraining runs.
CREATE TABLE IF NOT EXISTS admin_activity_log (
    id               INT AUTO_INCREMENT PRIMARY KEY,
    actor_identity   VARCHAR(100) NOT NULL,
    action           VARCHAR(80) NOT NULL,
    target_type      VARCHAR(80),
    target_identifier VARCHAR(120),
    details          JSON,
    created_at       DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_admin_activity_created_at (created_at),
    INDEX idx_admin_activity_actor (actor_identity)
);
