ALTER TABLE users
    ADD COLUMN IF NOT EXISTS legal_consent BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS terms_accepted_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS privacy_accepted_at DATETIME NULL;
